baseURL = 'https://finstar.github.io/'
languageCode = 'de-de'
title = 'Jensipedia'
theme = 'gokarna'
enableEmoji = true
enableRobotsTXT = true

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.png"
  AvatarAltText = "avatar von Jens"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "Spiel, Spass und Technik"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo", "MacOS", "3D Printer"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = ""

  # Footer text
  footer = "The Juns"


  [menu]
    [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/FinsTar"
    weight = 5
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
  
  [[menu.main]]
    name = "About"
    identifier = "abut"
    url = "/about/"
    weight = 6
    pre = "<span data-feather='user'></span>"